version: "3.4"
services:
    nopcommerce_web:
        build: .
        container_name: 4-nopcommerce-web
        ports:
            - "8080:80"
        depends_on:
            - nopcommerce_database
    nopcommerce_database:
        image: "microsoft/mssql-server-linux"
        ports:
            - "1433:1433"
        volumes:
            - /mnt/docker/microsoft-mssql-server-linux/mssql:/var/opt/mssql
        container_name: 4-nopcommerce-mssql
        environment:
            SA_PASSWORD: "ZPqnBPj6ZfETHVGGqpYrWuVV6sd8JCKc"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Express"
volumes:
  nopcommerce_data:
